### ISSUE TITLE
Internal error when clicking on watch numbers above page

### ISSUE THREAD

**Issue by djflux** [djflux/WatchAnalytics#2]
The following internal error occurs when click on one of the numbers above a watch page:

```
[Y9Vr_laAMiN60kjDfNpPEwAAAMg] /demo/index.php?title=Special:PageStatistics&page=Main+Page&requestDebug Error: Call to undefined method Title::isWatchable()

Backtrace:

from /opt/htdocs/mediawiki/extensions/WatchAnalytics/specials/SpecialPageStatistics.php(38)
#0 /opt/htdocs/mediawiki/includes/specialpage/SpecialPage.php(701): SpecialPageStatistics->execute(NULL)
#1 /opt/htdocs/mediawiki/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run(NULL)
#2 /opt/htdocs/mediawiki/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#3 /opt/htdocs/mediawiki/includes/MediaWiki.php(904): MediaWiki->performRequest()
#4 /opt/htdocs/mediawiki/includes/MediaWiki.php(562): MediaWiki->main()
#5 /opt/htdocs/mediawiki/index.php(50): MediaWiki->run()
#6 /opt/htdocs/mediawiki/index.php(46): wfIndexMain()
#7 {main}
```

**Comment by djflux** [comment]
See the following for a related fix:

https://github.com/wikimedia/mediawiki/commit/c3557c0f4f1d7087b4e87e7371e4ef3a2b996438

**Comment by djflux** [comment]
Commit 231047e018b0d901062f7df237df130b5559a013 resolves this issue
